### PR TITLE
Bundle "ninja_syntax.py" into the wheel

### PR DESCRIPTION
**Pull request by jcfr**
To maintain backward compatibility with existing ninja wheels, this
commit includes "ninja_syntax.py".

Suggested-by: Marat Dukhan <maratek@gmail.com>

### CODE REVIEW

**Comment by Maratyszcza** [comment]
LGTM, please merge before you upload the PyPI package.

**Comment by jcfr** [comment]
@Maratyszcza Will do. And will make sure the CI is green before doing so.

Note also that the next version of the package will be `1.7.2` so that it matches the version of ninja.

**Comment by jcfr** [comment]
Integrated as https://github.com/scikit-build/ninja-python-distributions/commit/ee84aedab365b811fe61ff2739d10f988ba81c9e

**Comment by jcfr** [comment]
Tag for 1.7.2 has been pushed https://github.com/scikit-build/ninja-python-distributions/releases/tag/1.7.2

**Comment by jcfr** [comment]
Associate packages will be uploaded as soon Appveyor, CircleCI and Travis are done generating them.

**Comment by jcfr** [comment]
Et voila, see https://pypi.python.org/pypi/ninja/1.7.2

**Pull request closed without merging**
