### PR TITLE
Update ninja to 1.9.0.g5b44b.kitware.dyndep-1.jobserver-1

### PR DESCRIPTION
**Pull request by kjerstadius**
Not much to say really. Just update the ninja binaries to the latest version.

### CODE REVIEW

**Comment by jcfr** [comment]
Todo (Jc):
* Create a branch named `1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.support-vs2008-vs2010` based of [kitware-staged-features-support-vs2008-vs2010](https://github.com/jcfr/ninja/tree/kitware-staged-features-support-vs2008-vs2010) used to build windows wheel for python 2.7 and 3.4. See [here](https://github.com/scikit-build/ninja-python-distributions/pull/17/files#diff-d5a060b71854c8cdabb0108bc78c0669L12).

**Comment by kjerstadius** [comment]
Just as I sat down to rebase this change I saw that you did @jcfr. Thanks! Not entirely sure what the issue that's coming up in CI builds are related to though. I can see that the name assertion fails, but unless I'm mistaken the filename with `.git.` rather than `.g5b44b` in the name seems to come from the built archive. Did something go wrong with the binary creation "upstream"? Or is it somehow related to your todo? I did notice the removal of those lines you mentioned related to MSVC. I didn't know what to make of it really, so I just made the change and hoped that it would work :) In any case, let me know if you need me to do anything.

**Comment by jcfr** [comment]
Thanks @kjerstadius  for looking into this. 

I am having a look and should get everything sorted out by the end of the day (EST time)

**Comment by jcfr** [comment]
The specific branch is not needed anymore, compat with older Visual Studio was fixed in https://github.com/ninja-build/ninja/commit/0db30f237ccc66a4fdf19d88666fc1f7e415a562

**Comment by jcfr** [comment]
Few jobs failed because of issue with upload to codecov.io. I manually retriggered the failed job.

**Pull request merged**
