### PR TITLE
fix travis twine and prepare for release

### PR DESCRIPTION
**Pull request by AWSjswinney**
I made some similar changes as were necessary for [cmake](https://github.com/scikit-build/cmake-python-distributions/pull/121/files). I also updated the readme, to link to the correct Travis builds. After merging this PR, could you make a tag to upload a new release to pypi?

### CODE REVIEW

**Comment by AWSjswinney** [comment]
Looks like this failures are caused by a regression in the `bdist_wheel` code. See the linked issue above.

**Comment by jcfr** [comment]
> Looks like this failures are caused by a regression

Thanks for following up on this 🙏 

Based on the upstream project answer, I guess we could mitigate the issue by installing an older version of wheel if python 2.7 is used ?

**Comment by AWSjswinney** [comment]
The Python 2.7 issues is resolved now, but there are still some other problems that seem like they're probably unrelated too. I'm looking to see what can be down about those problems.

**Comment by AWSjswinney** [comment]
@jfcr Can I get you to take a look at the mac build for Python 3? I'm not sure what's wrong and the error messages are not helping me:
https://travis-ci.com/github/scikit-build/ninja-python-distributions/jobs/461954832
Thank you!

**Comment by thewtex** [comment]
Perhaps GitHub Actions instead for the Travis build?

**Comment by henryiii** [comment]
@jcfr looks like you renamed the file but didn't update where it was getting called, perhaps?

**Comment by jcfr** [comment]
> looks like you renamed the file but didn't update where it was getting called, perhaps?

Good point, I missed that. I will split the commit and address the renaming issue.

**Pull request merged**
